### ISSUE TITLE
modpath-v7 does not compile with pymake

### ISSUE THREAD

**Issue by jlarsen-usgs** [MODFLOW-USGS/modpath-v7#25]
Please see linked issue in the pymake repository

[https://github.com/modflowpy/pymake/issues/93](https://github.com/modflowpy/pymake/issues/93)

**Comment by aprovost-usgs** [comment]
@jlarsen-usgs @Matt-Webb1 Thanks for bringing this to my attention. I'll consider the best way to reconfigure it in the long run, but in the meantime try replacing the current contents of makebin.bat with this:

**python -m pymake ../source ../msvs/bin/x64/Release/mpath7.exe --subdirs -fc ifort -mc -ar intel64
python -m pymake ../source ../msvs/bin/Win32/Release/mpath7_win32.exe --subdirs -fc ifort -mc -ar ia32
pause**

This simply runs pymake from the command line, avoiding the python script.

**Comment by Matt-Webb1** [comment]
Thanks @aprovost-usgs , I tried replacing the makebin.bat with the text you suggested and it didn't work for me. I got the following errors:


```
E:\Users\Matt\Desktop\modpath-v7\pymake>python -m pymake ../source ../msvs/bin/x64/Release/mpath7.exe --subdirs -fc ifort -mc -ar intel64
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 809, in _pymake_compile
    _create_win_batch(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 1042, in _create_win_batch
    raise Exception("Could not find cpvars: {}".format(cpvars))
Exception: Could not find cpvars: C:\Program Files (x86)\Intel\oneAPI\setvars.bat
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 809, in _pymake_compile
    _create_win_batch(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 1042, in _create_win_batch
    raise Exception("Could not find cpvars: {}".format(cpvars))
Exception: Could not find cpvars: C:\Program Files (x86)\Intel\oneAPI\setvars.bat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\__main__.py", line 10, in <module>
    main(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 256, in main
    returncode = _pymake_compile(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 830, in _pymake_compile
    errmsg += traceback.print_exc()
TypeError: can only concatenate str (not "NoneType") to str

E:\Users\Matt\Desktop\modpath-v7\pymake>python -m pymake ../source ../msvs/bin/Win32/Release/mpath7_win32.exe --subdirs -fc ifort -mc -ar ia32
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 809, in _pymake_compile
    _create_win_batch(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 1042, in _create_win_batch
    raise Exception("Could not find cpvars: {}".format(cpvars))
Exception: Could not find cpvars: C:\Program Files (x86)\Intel\oneAPI\setvars.bat
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 809, in _pymake_compile
    _create_win_batch(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 1042, in _create_win_batch
    raise Exception("Could not find cpvars: {}".format(cpvars))
Exception: Could not find cpvars: C:\Program Files (x86)\Intel\oneAPI\setvars.bat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\__main__.py", line 10, in <module>
    main(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 256, in main
    returncode = _pymake_compile(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 830, in _pymake_compile
    errmsg += traceback.print_exc()
TypeError: can only concatenate str (not "NoneType") to str

E:\Users\Matt\Desktop\modpath-v7\pymake>pause
Press any key to continue . . .
```

**Comment by christianlangevin** [comment]
It looks like you have the oneapi version of the Intel compilers.  I'm not sure we have tested that on Windows yet with pymake, so there may be a little work still to do on our end.

**Comment by Matt-Webb1** [comment]
Ah no worries - is there one that you could recommend as an alternative for Windows?

**Comment by christianlangevin** [comment]
It looks like @jdhughes-usgs added pymake support for Intel oneapi on June 22.  But it looks like oneapi has to be installed in the default location: `C:\\Program Files (x86)\\Intel\\oneAPI`.  Is that where you have it installed?

**Comment by Matt-Webb1** [comment]
That makes sense , I did notice the error in the terminal mentioned c:\\program files... and I was going to see if there was a way to work around that. I have oneAPI installed on my E drive since my C: is pretty small.

**Comment by Matt-Webb1** [comment]
Just an FYI - moving oneAPI to C: drive worked. Thanks!
